version: "3.8"

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    networks:
      - postgres-network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

volumes:
  postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge
    external: true
